# -*- coding: utf-8 -*-
"""exp017 standard shift k12 k16 hunt again.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCAEOzbnPzWwBMaNfbGVA0PEuHRdxonR
"""

import numpy as np
from sympy import sqrt, Rational, pi, sin, cos, symbols, N
import matplotlib.pyplot as plt
from itertools import product
import warnings
warnings.filterwarnings('ignore')

# ============================================================================
# EXP017: SEARCH FOR REVIVALS IN LARGE CYCLES WITH STANDARD SHIFT
# Testing k = 12, 16, 20, 24
# ============================================================================

class StandardShiftRevivalSearch:
    def __init__(self, k):
        self.k = k
        self.dim = 2 * k
        print(f"\n{'='*70}")
        print(f"SEARCHING FOR REVIVALS IN k={k}-CYCLE")
        print(f"Using STANDARD shift operator (|0⟩→, |1⟩←)")
        print(f"{'='*70}")

        # Dukes' known parameter forms to test
        self.parameter_forms = self.generate_parameter_forms()

    def shift_operator_standard(self):
        """
        STANDARD shift operator - THIS IS THE CORRECT ONE!
        Coin |0⟩ moves forward (right): |0⟩|j⟩ → |0⟩|j+1⟩
        Coin |1⟩ moves backward (left):  |1⟩|j⟩ → |1⟩|j-1⟩
        """
        S = np.zeros((self.dim, self.dim), dtype=complex)
        for pos in range(self.k):
            next_pos = (pos + 1) % self.k
            prev_pos = (pos - 1) % self.k
            S[next_pos, pos] = 1.0              # |0⟩ moves forward
            S[self.k + prev_pos, self.k + pos] = 1.0  # |1⟩ moves backward
        return S

    def coin_operator(self, rho, delta):
        """
        Coin operator with phase convention based on δ

        CRITICAL: For standard shift, the phase convention is the same:
        - For δ = 0 or π: use α = δ, β = 0
        - For δ = π/2 or 3π/2: use α = β = δ/2
        """
        delta_mod = delta % (2*np.pi)

        if abs(delta_mod) < 1e-10 or abs(delta_mod - np.pi) < 1e-10:
            alpha, beta = delta, 0
            conv = "standard"
        else:
            alpha = beta = delta/2
            conv = "symmetric"

        # Handle ρ > 1 case (√ρ becomes imaginary)
        sqrt_rho = np.sqrt(rho) if rho >= 0 else 1j * np.sqrt(-rho)
        if (1 - rho) >= 0:
            sqrt_1mr = np.sqrt(1 - rho)
        else:
            sqrt_1mr = 1j * np.sqrt(rho - 1)

        C = np.array([
            [sqrt_rho, sqrt_1mr * np.exp(1j * alpha)],
            [sqrt_1mr * np.exp(1j * beta), -sqrt_rho * np.exp(1j * (alpha + beta))]
        ], dtype=complex)

        return C, conv

    def generate_parameter_forms(self):
        """
        Generate candidate ρ values based on Dukes' known forms:
        1. Simple rational numbers: a/b
        2. Quadratic surds: (a ± √b)/c
        3. Dukes' special forms from k=4,8,10
        """
        candidates = []

        # Level 1: Simple rational numbers
        rationals = [
            (1/2, "1/2"), (1/3, "1/3"), (2/3, "2/3"), (1/4, "1/4"),
            (3/4, "3/4"), (1/5, "1/5"), (2/5, "2/5"), (3/5, "3/5"),
            (4/5, "4/5"), (1/6, "1/6"), (5/6, "5/6"), (1/8, "1/8"),
            (3/8, "3/8"), (5/8, "5/8"), (7/8, "7/8"), (1/10, "1/10"),
            (3/10, "3/10"), (7/10, "7/10"), (9/10, "9/10")
        ]
        candidates.extend(rationals)

        # Level 2: Quadratic surds with √2
        sqrt2 = np.sqrt(2)
        quadratics = [
            ((2 + sqrt2)/4, "(2+√2)/4"), ((2 - sqrt2)/4, "(2-√2)/4"),
            ((2 + sqrt2)/2, "(2+√2)/2"), ((2 - sqrt2)/2, "(2-√2)/2"),
            ((1 + sqrt2)/2, "(1+√2)/2"), ((1 - sqrt2)/2, "(1-√2)/2"),
            ((3 + sqrt2)/4, "(3+√2)/4"), ((3 - sqrt2)/4, "(3-√2)/4"),
            ((5 + sqrt2)/8, "(5+√2)/8"), ((5 - sqrt2)/8, "(5-√2)/8"),
        ]
        candidates.extend(quadratics)

        # Level 3: Quadratic surds with √3
        sqrt3 = np.sqrt(3)
        quadratics_3 = [
            ((2 + sqrt3)/4, "(2+√3)/4"), ((2 - sqrt3)/4, "(2-√3)/4"),
            ((2 + sqrt3)/2, "(2+√3)/2"), ((2 - sqrt3)/2, "(2-√3)/2"),
            ((1 + sqrt3)/2, "(1+√3)/2"), ((1 - sqrt3)/2, "(1-√3)/2"),
            ((3 + sqrt3)/4, "(3+√3)/4"), ((3 - sqrt3)/4, "(3-√3)/4"),
        ]
        candidates.extend(quadratics_3)

        # Level 4: Quadratic surds with √5 (golden ratio related)
        sqrt5 = np.sqrt(5)
        quadratics_5 = [
            ((5 + sqrt5)/8, "(5+√5)/8"), ((5 - sqrt5)/8, "(5-√5)/8"),
            ((3 + sqrt5)/4, "(3+√5)/4"), ((3 - sqrt5)/4, "(3-√5)/4"),
            ((7 + 3*sqrt5)/8, "(7+3√5)/8"), ((7 - 3*sqrt5)/8, "(7-3√5)/8"),
            ((1 + sqrt5)/4, "(1+√5)/4"), ((1 - sqrt5)/4, "(1-√5)/4"),
            ((1 + sqrt5)/2, "(1+√5)/2 (φ)"), ((1 - sqrt5)/2, "(1-√5)/2"),
        ]
        candidates.extend(quadratics_5)

        # Remove duplicates (within tolerance)
        unique = []
        seen = set()
        for val, desc in candidates:
            rounded = round(val, 8)
            if rounded not in seen:
                seen.add(rounded)
                unique.append((val, desc))

        print(f"Generated {len(unique)} unique candidate ρ values")
        return unique

    def verify_revival(self, rho, delta, N, tol=1e-10, verbose=False):
        """
        Verify if U^N = I for given parameters
        Returns: (is_revival, fidelity, difference, eigenval_deviation)
        """
        # Build operators
        S = self.shift_operator_standard()
        C, conv = self.coin_operator(rho, delta)
        U = S @ np.kron(C, np.eye(self.k))

        # Initial state (standard initial state)
        psi0 = np.zeros(self.dim, dtype=complex)
        psi0[0] = np.sqrt(rho) if rho >= 0 else 0
        psi0[self.k] = np.sqrt(1 - rho) if (1-rho) >= 0 else 0
        psi0 = psi0 / np.linalg.norm(psi0)

        # Compute U^N and apply to initial state
        U_power = np.linalg.matrix_power(U, N)
        psiN = U_power @ psi0

        # Check fidelity with initial state (accounting for global phase)
        overlap = np.vdot(psi0, psiN)
        fidelity = np.abs(overlap)**2

        # Remove global phase to check exact equality
        phase = overlap / (np.abs(overlap) + 1e-15)
        psiN_phased = psiN / phase
        difference = np.linalg.norm(psi0 - psiN_phased)

        # Check eigenvalues (most rigorous test)
        eigenvals = np.linalg.eigvals(U)
        eigenval_N = eigenvals ** N
        eigenval_deviation = np.max(np.abs(eigenval_N - 1))

        is_revival = (difference < tol) and (eigenval_deviation < tol)

        if verbose and is_revival:
            print(f"\n✅ FOUND REVIVAL!")
            print(f"   k={self.k}, N={N}, ρ={rho:.10f} ({desc})")
            print(f"   δ/π={delta/np.pi:.2f}, Convention: {conv}")
            print(f"   Fidelity: {fidelity:.2e}")
            print(f"   Difference: {difference:.2e}")

        return {
            'is_revival': is_revival,
            'fidelity': fidelity,
            'difference': difference,
            'eigenval_deviation': eigenval_deviation,
            'convention': conv
        }

    def search(self, max_N=60, tolerance=1e-8):
        """
        Systematic search for revivals
        Tests N that are multiples of k/2, k, 2k, etc.
        """
        print(f"\n{'='*70}")
        print(f"SYSTEMATIC SEARCH FOR k={self.k}")
        print(f"{'='*70}")

        # Generate N values to test
        N_values = []
        for m in range(1, 11):
            N_values.append(m * self.k)  # multiples of k
            if self.k % 2 == 0:
                N_values.append(m * self.k // 2)  # half multiples

        N_values = sorted(list(set([n for n in N_values if n <= max_N])))

        # δ values to test (from Dukes' patterns)
        delta_values = [0, np.pi/2, np.pi, 3*np.pi/2]

        print(f"Testing N values: {N_values}")
        print(f"Testing δ values: [0, π/2, π, 3π/2]")
        print(f"Testing {len(self.parameter_forms)} ρ candidates")
        print(f"Total combinations: {len(N_values) * len(delta_values) * len(self.parameter_forms)}")

        discoveries = []

        for N in N_values:
            for delta in delta_values:
                for rho, desc in self.parameter_forms:
                    result = self.verify_revival(rho, delta, N, tol=tolerance)

                    if result['is_revival']:
                        discoveries.append({
                            'N': N,
                            'rho': rho,
                            'desc': desc,
                            'delta': delta,
                            'convention': result['convention'],
                            'fidelity': result['fidelity'],
                            'difference': result['difference']
                        })
                        print(f"\n✅ REVIVAL FOUND: k={self.k}, N={N}, ρ={rho:.8f} ({desc}), δ/π={delta/np.pi:.2f}")

        return discoveries


# ============================================================================
# MAIN SEARCH
# ============================================================================

def main():
    print("="*70)
    print("EXP017: SYSTEMATIC SEARCH FOR REVIVALS IN LARGE CYCLES")
    print("Using STANDARD shift operator (|0⟩→, |1⟩←)")
    print("Testing k = 12, 16, 20, 24")
    print("="*70)

    results = {}

    for k in [12, 16, 20, 24]:
        searcher = StandardShiftRevivalSearch(k)
        discoveries = searcher.search(max_N=60, tolerance=1e-8)
        results[k] = discoveries

        if discoveries:
            print(f"\n{'='*70}")
            print(f"SUMMARY FOR k={k}: Found {len(discoveries)} revivals")
            print(f"{'='*70}")
            for d in discoveries:
                print(f"  N={d['N']:2d}, ρ={d['rho']:.8f} ({d['desc']}), δ/π={d['delta']/np.pi:.2f}")
        else:
            print(f"\n{'='*70}")
            print(f"SUMMARY FOR k={k}: No revivals found")
            print(f"{'='*70}")

    # Final conclusion
    print("\n" + "="*70)
    print("FINAL CONCLUSION")
    print("="*70)

    for k in [12, 16, 20, 24]:
        if results[k]:
            print(f"k={k}: ✅ {len(results[k])} revivals found with STANDARD shift")
        else:
            print(f"k={k}: ❌ No revivals found with STANDARD shift")

    print("\n" + "="*70)
    print("Based on Dukes' tables, we know STANDARD shift revivals exist for:")
    print("k = 3, 4, 5, 6, 8, 10")
    print("\nThis search will tell us whether they exist for larger k.")
    print("="*70)


if __name__ == "__main__":
    main()