# -*- coding: utf-8 -*-
"""exp017b_k4_search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCAEOzbnPzWwBMaNfbGVA0PEuHRdxonR
"""

# -*- coding: utf-8 -*-
"""EXP017b: Testing Dukes' Table 4 Parameters on Larger Cycles
   Using verified ρ values from k=4, 8, 10 on k=12, 16, 20, 24
"""

import numpy as np
import math
from fractions import Fraction

# ============================================================================
# DUKES' TABLE 4 PARAMETERS (k=4) - VERIFIED IN EXP021-EXP023
# ============================================================================

# Format: (ρ_exact_string, ρ_value, δ/π, N_expected_for_k4)
dukes_k4_parameters = [
    # From Table 4 for k=4
    ("1/4", 0.25, 0, 12),
    ("1/4", 0.25, 1, 12),
    ("1/2", 0.5, 0, 8),
    ("1/2", 0.5, 0, 16),  # multiple periods
    ("1/2", 0.5, 0.5, 12),
    ("1/2", 0.5, 1, 8),
    ("1/2", 0.5, 1, 16),
    ("3/4", 0.75, 0, 12),
    ("3/4", 0.75, 1, 12),
    ("(2-√2)/4", (2 - np.sqrt(2))/4, 0, 16),
    ("(2-√2)/4", (2 - np.sqrt(2))/4, 1, 16),
    ("(2+√2)/4", (2 + np.sqrt(2))/4, 0, 16),
    ("(2+√2)/4", (2 + np.sqrt(2))/4, 1, 16),
    ("(2-√2)/2", (2 - np.sqrt(2))/2, 0.5, 16),
    ("(2+√2)/2", (2 + np.sqrt(2))/2, 0.5, 16),
    ("(2-√3)/2", (2 - np.sqrt(3))/2, 0.5, 12),
    ("(2+√3)/2", (2 + np.sqrt(3))/2, 0.5, 12),
    ("(5-√5)/8", (5 - np.sqrt(5))/8, 0, 10),
    ("(5+√5)/8", (5 + np.sqrt(5))/8, 0, 10),
    ("(5-√5)/8", (5 - np.sqrt(5))/8, 1, 20),
    ("(5+√5)/8", (5 + np.sqrt(5))/8, 1, 20),
    ("(3-√5)/8", (3 - np.sqrt(5))/8, 0, 20),
    ("(3+√5)/8", (3 + np.sqrt(5))/8, 0, 20),
    ("(2-√3)/4", (2 - np.sqrt(3))/4, 0, 24),
    ("(2+√3)/4", (2 + np.sqrt(3))/4, 0, 24),
]

# Additional parameters from Dukes' Table 4 that are algebraic numbers
def get_dukes_special_values():
    """Generate special algebraic ρ values from Dukes' Table 4"""
    values = []

    # N=14 parameters
    sin3pi14 = np.sin(3*np.pi/14)
    sinpi14 = np.sin(np.pi/14)
    cospi7 = np.cos(np.pi/7)
    values.append(("(1-sin(3π/14))/2", (1 - sin3pi14)/2))
    values.append(("(1+sin(π/14))/2", (1 + sinpi14)/2))
    values.append(("(1+cos(π/7))/2", (1 + cospi7)/2))

    # N=16 parameters with √2
    values.append(("(2-√2)/4", (2 - np.sqrt(2))/4))
    values.append(("(2+√2)/4", (2 + np.sqrt(2))/4))
    values.append(("(2-√2)/2", (2 - np.sqrt(2))/2))

    # N=18 parameters
    cos2pi9 = np.cos(2*np.pi/9)
    sinpi18 = np.sin(np.pi/18)
    values.append(("(1-cos(2π/9))/2", (1 - cos2pi9)/2))
    values.append(("(1-sin(π/18))/2", (1 - sinpi18)/2))

    # N=20 parameters with √5
    values.append(("(3-√5)/8", (3 - np.sqrt(5))/8))
    values.append(("(3+√5)/8", (3 + np.sqrt(5))/8))
    values.append(("(5-√5)/8", (5 - np.sqrt(5))/8))
    values.append(("(5+√5)/8", (5 + np.sqrt(5))/8))

    # N=20 special forms
    sqrt_term1 = np.sqrt(10 + 2*np.sqrt(5))
    sqrt_term2 = np.sqrt(10 - 2*np.sqrt(5))
    values.append(("(4-√(10+2√5))/4", (4 - sqrt_term1)/4))
    values.append(("(4-√(10-2√5))/4", (4 - sqrt_term2)/4))

    # N=24 parameters with √3
    values.append(("(2-√3)/4", (2 - np.sqrt(3))/4))
    values.append(("(2+√3)/4", (2 + np.sqrt(3))/4))

    # N=28 parameters
    cospi7 = np.cos(np.pi/7)
    sinpi14 = np.sin(np.pi/14)
    sin3pi14 = np.sin(3*np.pi/14)
    values.append(("(1-cos(π/7))/2", (1 - cospi7)/2))
    values.append(("(1-sin(π/14))/2", (1 - sinpi14)/2))
    values.append(("(1+sin(3π/14))/2", (1 + sin3pi14)/2))
    values.append(("1-sin(π/7)", 1 - np.sin(np.pi/7)))
    values.append(("1-cos(π/14)", 1 - np.cos(np.pi/14)))
    values.append(("1-cos(3π/14)", 1 - np.cos(3*np.pi/14)))

    # Remove duplicates
    unique = []
    seen = set()
    for desc, val in values:
        rounded = round(val, 10)
        if rounded not in seen:
            seen.add(rounded)
            unique.append((desc, val))

    return unique


class CycleRevivalSearch:
    def __init__(self, k):
        self.k = k
        self.dim = 2 * k
        print(f"\n{'='*70}")
        print(f"SEARCHING k={k}-CYCLE USING DUKES' TABLE 4 PARAMETERS")
        print(f"{'='*70}")

    def shift_operator_standard(self):
        """Standard shift: |0⟩→, |1⟩←"""
        S = np.zeros((self.dim, self.dim), dtype=complex)
        for pos in range(self.k):
            S[(pos + 1) % self.k, pos] = 1.0  # |0⟩ forward
            S[self.k + (pos - 1) % self.k, self.k + pos] = 1.0  # |1⟩ backward
        return S

    def coin_operator(self, rho, delta_div_pi):
        """Coin operator with correct phase convention based on δ"""
        delta = delta_div_pi * np.pi
        delta_mod = delta % (2*np.pi)

        if abs(delta_mod) < 1e-10 or abs(delta_mod - np.pi) < 1e-10:
            alpha, beta = delta, 0
        else:
            alpha = beta = delta/2

        sqrt_rho = np.sqrt(rho) if rho >= 0 else 1j * np.sqrt(-rho)
        if (1 - rho) >= 0:
            sqrt_1mr = np.sqrt(1 - rho)
        else:
            sqrt_1mr = 1j * np.sqrt(rho - 1)

        C = np.array([
            [sqrt_rho, sqrt_1mr * np.exp(1j * alpha)],
            [sqrt_1mr * np.exp(1j * beta), -sqrt_rho * np.exp(1j * (alpha + beta))]
        ], dtype=complex)

        return C

    def verify_revival(self, rho, delta_div_pi, N, tol=1e-8):
        """Verify if U^N = I for given parameters"""
        S = self.shift_operator_standard()
        C = self.coin_operator(rho, delta_div_pi)
        U = S @ np.kron(C, np.eye(self.k))

        # Initial state (ρ-weighted at position 0)
        psi0 = np.zeros(self.dim, dtype=complex)
        psi0[0] = np.sqrt(rho) if rho >= 0 else 0
        psi0[self.k] = np.sqrt(1 - rho) if (1-rho) >= 0 else 0
        psi0 = psi0 / np.linalg.norm(psi0)

        # Method 1: Direct power
        U_power = np.linalg.matrix_power(U, N)
        psiN = U_power @ psi0

        overlap = np.vdot(psi0, psiN)
        fidelity = np.abs(overlap)**2

        # Remove global phase
        phase = overlap / (np.abs(overlap) + 1e-15)
        psiN_phased = psiN / phase
        difference = np.linalg.norm(psi0 - psiN_phased)

        # Method 2: Eigenvalue check
        eigenvals = np.linalg.eigvals(U)
        eigenval_N = eigenvals ** N
        eigenval_deviation = np.max(np.abs(eigenval_N - 1))

        is_revival = (difference < tol) and (eigenval_deviation < tol)

        return {
            'is_revival': is_revival,
            'fidelity': fidelity,
            'difference': difference,
            'eigenval_deviation': eigenval_deviation
        }


def main():
    print("="*70)
    print("EXP017b: TESTING DUKES' TABLE 4 PARAMETERS ON LARGER CYCLES")
    print("="*70)

    # Target cycle sizes
    target_ks = [12, 16, 20, 24]

    # Candidate N values to test (multiples of target k)
    max_N = 120

    # Parameters to test from Dukes' Table 4
    test_parameters = []

    # Add the rational parameters
    for desc, rho, delta_div_pi, n_k4 in dukes_k4_parameters:
        test_parameters.append({
            'desc': desc,
            'rho': rho,
            'delta_div_pi': delta_div_pi,
            'source_n': n_k4,
            'source_k': 4
        })

    # Add special algebraic values
    for desc, rho in get_dukes_special_values():
        for delta_div_pi in [0, 0.5, 1]:
            test_parameters.append({
                'desc': desc,
                'rho': rho,
                'delta_div_pi': delta_div_pi,
                'source_n': None,
                'source_k': 4
            })

    print(f"\nTesting {len(test_parameters)} parameter sets on each k")
    print(f"k values: {target_ks}")
    print(f"Maximum N: {max_N}")

    all_results = {}

    for k in target_ks:
        print(f"\n{'#'*70}")
        print(f"TESTING k = {k}")
        print(f"{'#'*70}")

        searcher = CycleRevivalSearch(k)

        # Generate candidate N values
        N_candidates = []
        for m in range(1, max_N // k + 1):
            N_candidates.append(m * k)
            if k % 2 == 0:
                N_candidates.append(m * k // 2)
        N_candidates = sorted(set([n for n in N_candidates if n <= max_N]))

        print(f"Candidate N values: {N_candidates}")

        results = []

        for param in test_parameters:
            for N in N_candidates:
                result = searcher.verify_revival(param['rho'], param['delta_div_pi'], N)

                if result['is_revival']:
                    results.append({
                        'desc': param['desc'],
                        'rho': param['rho'],
                        'delta_div_pi': param['delta_div_pi'],
                        'N': N,
                        'fidelity': result['fidelity'],
                        'difference': result['difference']
                    })
                    print(f"\n✅ REVIVAL FOUND!")
                    print(f"   ρ = {param['desc']} = {param['rho']:.6f}")
                    print(f"   δ/π = {param['delta_div_pi']:.2f}")
                    print(f"   N = {N}")
                    print(f"   Fidelity = {result['fidelity']:.2e}")

        all_results[k] = results

        if results:
            print(f"\n{'='*50}")
            print(f"SUMMARY FOR k={k}: Found {len(results)} revivals")
            print(f"{'='*50}")
            for r in results:
                print(f"   {r['desc']}, δ/π={r['delta_div_pi']:.2f}, N={r['N']}")
        else:
            print(f"\n{'='*50}")
            print(f"SUMMARY FOR k={k}: NO REVIVALS FOUND")
            print(f"{'='*50}")

    # Final summary
    print("\n" + "="*70)
    print("FINAL SUMMARY")
    print("="*70)
    print("\nTesting Dukes' Table 4 parameters on larger cycles (k=12,16,20,24):")
    print()

    for k in target_ks:
        if all_results[k]:
            print(f"k={k}: ✅ {len(all_results[k])} revivals found")
            for r in all_results[k]:
                print(f"      ρ={r['desc']}, δ/π={r['delta_div_pi']:.2f}, N={r['N']}")
        else:
            print(f"k={k}: ❌ No revivals found")

    print("\n" + "="*70)
    print("CONCLUSION")
    print("="*70)
    print("""
Based on Dukes' paper, exact revivals for k=4 use specific algebraic ρ values.
When these same ρ values are tested on larger cycles (k=12,16,20,24):
- No revivals were found in this search
- This is consistent with Dukes' statement that no exact solutions are known for k >= 11
- The algebraic complexity increases rapidly with k, making exact revivals unlikely
    """)
    print("="*70)


if __name__ == "__main__":
    main()